### ISSUE TITLE
pip-custom-platform with no arguments produces useless traceback

### ISSUE THREAD

**Issue by chriskuehl** [asottile/pip-custom-platform#3]
```
(venv) ckuehl@dementors:~/proj/linux-wheels$ pip-custom-platform       
Traceback (most recent call last):
  File "/home/c/ck/ckuehl/proj/linux-wheels/venv/bin/pip-custom-platform", line 11, in <module>
    sys.exit(main())
  File "/home/c/ck/ckuehl/proj/linux-wheels/venv/lib/python3.4/site-packages/pip_custom_platform/main.py", line 42, in main
    platform = args.platform.replace('-', '_')
AttributeError: 'Namespace' object has no attribute 'platform'
```
Python 3.4, in virtualenv, on Debian jessie

**Comment by chriskuehl** [comment]
On Python2.7:
```
(tmp.hh3e4PQckO)ckuehl@dementors:~/proj/linux-wheels$ pip-custom-platform
usage: pip-custom-platform [-h] {install,wheel} ...
pip-custom-platform: error: too few arguments
```

On Python3.4:
```
(tmp.2vEHGvfmjK)ckuehl@dementors:~/proj/linux-wheels$ pip-custom-platform
Traceback (most recent call last):
  File "/tmp/tmp.2vEHGvfmjK/bin/pip-custom-platform", line 9, in <module>
    load_entry_point('pip-custom-platform==0.2.0', 'console_scripts', 'pip-custom-platform')()
  File "/home/c/ck/ckuehl/proj/pip-custom-platform/pip_custom_platform/main.py", line 42, in main
    platform = args.platform.replace('-', '_')
AttributeError: 'Namespace' object has no attribute 'platform'
```


Looks like this issue:
http://stackoverflow.com/questions/23349349/argparse-with-required-subparser

**Comment by asottile** [comment]
Yep, this also happens on trusty.

I was wondering why pre-commit doesn't hit this, it seems it's because of my "default parser" logic: https://github.com/pre-commit/pre-commit/blob/00c853b10cc6ff1548f442362f1e2c7541ecaad7/pre_commit/main.py#L123
