### ISSUE TITLE
pip version compatibility

### ISSUE THREAD

**Issue by jayvdb** [asottile/pip-custom-platform#30]
It would be helpful to have setup.cfg narrow down the version range of `pip` which are supported/tested, and include CI for the earliest supported pip known to work.  This is pretty funky hacking and is unavoidably brittle and as you will know pip frequently breaks backwards compatibility intentionally.

When using python 3.7's default venv or virtualenv preinstalled pip, I get the following, which I guess is because `pip._internal` had not finished being imported:

```py
[  126s] E           subprocess.CalledProcessError: Command '('/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/bin/python', '-m', 'coverage', 'run', '-m', 'pip_custom_platform.main', 'show-platform-name')' returned non-zero exit status 1.
[  126s] 
[  126s] /usr/lib64/python3.7/subprocess.py:347: CalledProcessError
[  126s] ----------------------------- Captured stderr call -----------------------------
[  126s] Traceback (most recent call last):
[  126s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/pip_custom_platform/main.py", line 9, in <module>
[  126s]     exit(main())
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 270, in entry
[  126s]     tuple(patches) + ('--', original_entry_point) + tuple(argv)
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 258, in main
[  126s]     return entry.load()()
[  126s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
[  126s]     return self.resolve()
[  126s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
[  126s]     module = __import__(self.module_name, fromlist=['__name__'], level=0)
[  126s]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[  126s]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 173, in load_module
[  126s]     module = importmod(fullname)
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 94, in importmod
[  126s]     return __import__(mod, fromlist=[str('__name__')], level=0)
[  126s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/lib64/python3.7/site-packages/pip/_internal/__init__.py", line 40, in <module>
[  126s]     from pip._internal.cli.autocompletion import autocomplete
[  126s]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[  126s]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 173, in load_module
[  126s]     module = importmod(fullname)
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 94, in importmod
[  126s]     return __import__(mod, fromlist=[str('__name__')], level=0)
[  126s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/lib64/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
[  126s]     from pip._internal.cli.main_parser import create_main_parser
[  126s]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[  126s]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 173, in load_module
[  126s]     module = importmod(fullname)
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 94, in importmod
[  126s]     return __import__(mod, fromlist=[str('__name__')], level=0)
[  126s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/lib64/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
[  126s]     from pip._internal.commands import (
[  126s]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[  126s]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 173, in load_module
[  126s]     module = importmod(fullname)
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 94, in importmod
[  126s]     return __import__(mod, fromlist=[str('__name__')], level=0)
[  126s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/lib64/python3.7/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
[  126s]     from pip._internal.commands.completion import CompletionCommand
[  126s]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[  126s]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 173, in load_module
[  126s]     module = importmod(fullname)
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 94, in importmod
[  126s]     return __import__(mod, fromlist=[str('__name__')], level=0)
[  126s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/lib64/python3.7/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
[  126s]     from pip._internal.cli.base_command import Command
[  126s]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[  126s]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 173, in load_module
[  126s]     module = importmod(fullname)
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 94, in importmod
[  126s]     return __import__(mod, fromlist=[str('__name__')], level=0)
[  126s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/lib64/python3.7/site-packages/pip/_internal/cli/base_command.py", line 25, in <module>
[  126s]     from pip._internal.index import PackageFinder
[  126s]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[  126s]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 173, in load_module
[  126s]     module = importmod(fullname)
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 94, in importmod
[  126s]     return __import__(mod, fromlist=[str('__name__')], level=0)
[  126s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/lib64/python3.7/site-packages/pip/_internal/index.py", line 32, in <module>
[  126s]     from pip._internal.pep425tags import get_supported
[  126s]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[  126s]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
[  126s]   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
[  126s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 175, in load_module
[  126s]     hook_fn(module, self._entry_data[entry])
[  126s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/pip_custom_platform/pymonkey.py", line 17, in pymonkey_patch
[  126s]     mod.supported_tags = mod.get_supported()
[  126s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/lib64/python3.7/site-packages/pip/_internal/pep425tags.py", line 340, in get_supported
[  126s]     if is_manylinux2010_compatible():
[  126s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/lib64/python3.7/site-packages/pip/_internal/pep425tags.py", line 196, in is_manylinux2010_compatible
[  126s]     return pip._internal.utils.glibc.have_compatible_glibc(2, 12)
[  126s] AttributeError: module 'pip' has no attribute '_internal'
```

When I use pip 19.3.1

```py
[  110s] _____________________________ test_pymonkey_patch ______________________________
[  110s] 
[  110s] tmpdir = local('/tmp/pytest-of-abuild/pytest-0/test_pymonkey_patch0')
[  110s] 
[  110s]     def test_pymonkey_patch(tmpdir):
[  110s]         findlinks_dir = tmpdir.join('findlinks_dir').strpath
[  110s]         download_dest = tmpdir.join('downloads').mkdir().strpath
[  110s]     
[  110s]         call_coverage(
[  110s]             '-m', 'pymonkey', 'pip-custom-platform', '--', 'uses-pip',
[  110s]             '--platform', 'plat1',
[  110s]             findlinks_dir, download_dest,
[  110s] >           'testing/project_with_c', 'project-with-c',
[  110s]         )
[  110s] 
[  110s] tests/main_test.py:179: 
[  110s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  110s] tests/main_test.py:14: in call_coverage
[  110s]     subprocess.check_call((sys.executable, '-m', 'coverage', 'run') + cmd)
[  110s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  110s] 
[  110s] popenargs = (('/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/bin/python', '-m', 'coverage', 'run', '-m', 'pymonkey', ...),)
[  110s] kwargs = {}, retcode = 1
[  110s] cmd = ('/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/bin/python', '-m', 'coverage', 'run', '-m', 'pymonkey', ...)
[  110s] 
[  110s]     def check_call(*popenargs, **kwargs):
[  110s]         """Run command with arguments.  Wait for command to complete.  If
[  110s]         the exit code was zero then return, otherwise raise
[  110s]         CalledProcessError.  The CalledProcessError object will have the
[  110s]         return code in the returncode attribute.
[  110s]     
[  110s]         The arguments are the same as for the call function.  Example:
[  110s]     
[  110s]         check_call(["ls", "-l"])
[  110s]         """
[  110s]         retcode = call(*popenargs, **kwargs)
[  110s]         if retcode:
[  110s]             cmd = kwargs.get("args")
[  110s]             if cmd is None:
[  110s]                 cmd = popenargs[0]
[  110s] >           raise CalledProcessError(retcode, cmd)
[  110s] E           subprocess.CalledProcessError: Command '('/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testenv/bin/python', '-m', 'coverage', 'run', '-m', 'pymonkey', 'pip-custom-platform', '--', 'uses-pip', '--platform', 'plat1', '/tmp/pytest-of-abuild/pytest-0/test_pymonkey_patch0/findlinks_dir', '/tmp/pytest-of-abuild/pytest-0/test_pymonkey_patch0/downloads', 'testing/project_with_c', 'project-with-c')' returned non-zero exit status 1.
[  110s] 
[  110s] /usr/lib64/python3.7/subprocess.py:347: CalledProcessError
[  110s] ----------------------------- Captured stderr call -----------------------------
[  110s] /usr/lib/python3.7/site-packages/pymonkey.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
[  110s]   import imp
[  110s] Traceback (most recent call last):
[  110s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 277, in <module>
[  110s]     sys.exit(main())
[  110s]   File "/usr/lib/python3.7/site-packages/pymonkey.py", line 258, in main
[  110s]     return entry.load()()
[  110s]   File "/home/abuild/rpmbuild/BUILD/pip-custom-platform-0.5.0/testing/uses_pip/uses_pip.py", line 12, in main
[  110s]     assert not pip_main(['wheel', pkg, '--wheel-dir', findlinks])
[  110s] TypeError: 'module' object is not callable
```

I havent investigated that last one at all.  fwiw, the reason I am trying to get this working is trying to control pip to fetch the appropriate target needed by an invocation of https://github.com/indygreg/PyOxidizer

**Comment by asottile** [comment]
upper bounding the version is not a maintainable approach to python packaging so I won't do that (_usually_ a new release works just fine)

this appears to be the main function movement, would you like to take a stab at a patch?

**Comment by jayvdb** [comment]
> earliest supported pip known to work

I was asking about lower bound. Do you know it?

I'm of the same opinion re upper bounds creating more trouble than they solve.

I can take a look at fixing it, but cant commit to it in next few days due to other pending work.

**Comment by asottile** [comment]
afaik it works all the way back to pip 1.4 (2013)

**Comment by jayvdb** [comment]
A lower bound that low isnt worth adding, and agree upper bounds isnt useful, so closing.

Some packages which use pip internals list a pip 'supported version' and include that if there are import errors, but even that isnt sufficient if pip internals are modified in a non-breaking way, esp return types.

It might be worth switching to using pip-shims or pip-api (the author of this one is keen to add more functionality when needed, but can be a bit slow to respond/review), as most distros already maintain packages for those, keeping them up to date.
